### ISSUE TITLE
validateRDBESRawObject asking for columns that are not present in cl table

### ISSUE THREAD

**Issue by KatjaNoren** [ices-tools-dev/icesRDBES#27] opened 2022-09-27 12:24 UTC
validateRDBESRawObject asking for columns that are not present in CL table: CLeconZoneIndi,CLsciWeightRSE,CLvalRSE"

**Comment by nicolas-tku** [comment] 2022-09-30 09:31
likewise for CE table: CEeconZoneIndi,CEsciFishDayRSE

**Comment by davidcurrie2001** [comment] 2022-10-06 11:41
The function hadn't been updated for the most recent data model changes.  The latest version on the dev branch should now be using the field names from the most recent data model.

**Comment by KirstenBirchHaakansson** [comment] 2022-10-12 07:38
Subgroup 3 - we have tested the validateRDBESRawObject on Danish, Finnish and Scotish data and we are not able to reproduce, so we would close this issue

**Comment by KirstenBirchHaakansson** [comment] 2022-10-12 10:25
The problem is most likely a bug in the RDBES download. An issue has been raised at [https://github.com/ices-tools-dev/RDBES Issue number 1](https://github.com/ices-tools-dev/RDBES/issues/170), so we consider this issue closed from our side

**Closed** 2022-10-12 10:25 UTC
